# mnist, cifar-10 데이터 구조 살펴보기

In [ ]:
# 필요한 모듈 불러오기
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Flatten, Conv2D, MaxPooling2D, Dense
import pandas as pd

In [ ]:
# 데이터 다운받기
(train_x, train_y), (test_x, test_y) = tf.keras.datasets.mnist.load_data()
print(train_x.shape, train_y.shape)
print(test_x.shape, test_y.shape)

# 함수의 Default Parameter

In [ ]:
def add(a, b) :
    return a + b

print(add(2, 3))
print(add())
print(add(2))

In [ ]:
def subtract(a, b=3) :
    return a - b

print(subtract(5))
print(subtract(10, 20))

In [ ]:
def subtract(a, b=3) :
    return a - b

print(subtract(b=20, a=10))

In [ ]:
def add(a=2, b=3) :
    return a + b

print(add())
print(add(5))
print(add(10, 20))

# CNN 모델 개발

https://www.tensorflow.org/api_docs/python/tf  
> https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D  
> https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPooling2D

```
tf.keras.layers.Conv2D(
    filters, # 필터 개수
    kernel_size, # 커널 크기, 3 혹은 (3, 3)
    strides=(1, 1),  # 보폭
    padding='valid', # 패딩(valid, same 등)
    data_format=None,
    dilation_rate=(1, 1),
    groups=1,
    activation=None, # 활성화 함수
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    **kwargs
)
tf.keras.layers.MaxPooling2D(
    pool_size=(2, 2), # 풀링 필터 사이즈
    strides=None,
    padding='valid',
    data_format=None,
    **kwargs
)
```

In [ ]:
# 필요한 모듈 불러오기
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Flatten, Conv2D, MaxPooling2D, Dense
import pandas as pd

# 데이터 다운받기
(train_x, train_y), (test_x, test_y) = mnist.load_data()

# 데이터 전처리
train_x = train_x.reshape(60000, 28, 28, 1)   # 3차원 이미지를 넣어야 함.
train_x = train_x / 255.0

# 모델 설계
model = Sequential()
model.add(Input(shape=(28, 28, 1)))

model.add(Conv2D(6, kernel_size=(5, 5), activation='relu'))
model.add(MaxPool2D((2, 2)))

model.add(Conv2D(16, kernel_size=(5, 5), activation='relu'))
model.add(MaxPool2D((2, 2)))
model.add(Flatten())

model.add(Dense(120, activation='relu'))
model.add(Dense(84, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=32, epochs=10)

In [ ]:
model.summary()

# cifar-10 CNN

In [ ]:
# 필요한 모듈 불러오기
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Flatten, Conv2D, MaxPooling2D, Dense
import pandas as pd

# 데이터를 준비하고
(train_x, train_y), (test_x, test_y) = tf.keras.datasets.cifar10.load_data()

train_x = train_x / 255

# 모델을 만들고
model = Sequential()

model.add(Conv2D(6, (3, 3), input_shape=(32, 32, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(16, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(train_x, train_y, epochs=10)

# 모델 활용

In [ ]:
# 학습데이터(train_x)로도 분류해보고, 테스트데이터(test_x)로도 분류해 보자.
pred = model.predict(train_x)
pred

In [3]:
# 예측 값을 판다스 데이터 프레임으로  만들어 보자...
import pandas as pd

df_pred = ?????????
df_pred

0     1     2     3     4     5     6     7     8     9
0      0.00  0.00  0.00  0.10  0.00  0.23  0.66  0.01  0.00  0.00
1      0.00  0.02  0.00  0.00  0.00  0.00  0.00  0.02  0.00  0.95
2      0.02  0.01  0.06  0.12  0.00  0.03  0.01  0.01  0.01  0.73
3      0.00  0.00  0.01  0.00  0.83  0.00  0.15  0.00  0.00  0.00
4      0.05  0.93  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.02
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
49995  0.33  0.00  0.01  0.00  0.00  0.00  0.00  0.00  0.65  0.01
49996  0.01  0.00  0.25  0.48  0.08  0.06  0.10  0.01  0.00  0.00
49997  0.09  0.08  0.00  0.00  0.00  0.00  0.00  0.00  0.04  0.79
49998  0.19  0.27  0.00  0.00  0.02  0.00  0.00  0.00  0.44  0.08
49999  0.17  0.28  0.01  0.06  0.01  0.01  0.00  0.19  0.15  0.12

[50000 rows x 10 columns]

In [4]:
# 정답 데이터(train_y) 출력
train_y

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [5]:
# pred(예측값을 모아놓은 2차원 배열)에서 가장 큰 값의 인덱스 번호를
import numpy as np

pred_arr =
pred_arr

array([6, 9, 9, ..., 9, 8, 1])

In [8]:
# 정답데이터(train_y)를 2차원 --> 1차원 배열로 만들어 보자.
target_arr = ????????????????????
target_arr

array([6, 9, 9, ..., 9, 1, 1], dtype=uint8)

In [ ]:
# 예측값(pred_arr, 1차원 배열), 정답(target_arr, 1차원을) 을 비교하여 다른(오답)인 인덱스를 뽑아내자.

wrong = ????????????????
wrong

In [16]:
# cafar10의 번호별 객체

cifar_class = {0:"airplane", 1:"automobile", 2:"bird", 3:"cat", 4:"deer", 5:"dog", 6:"frog", 7:"horse", 8:"ship", 9:"truck"}

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize = (1,1))
plt.imshow(train_x[5])
print("예측 :", pred_arr[5])
print("정답 :", target_arr[5])

# 각자 더 성능 좋은 모델로 발전시켜 보기

In [ ]:
# 합성곱 층에서 커널(필터의 수)를 조절, 분류층에서 레이어나 노드 수를 조절해 성능을 개선해 보자...

# 필요한 모듈 불러오기
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Flatten, Conv2D, MaxPooling2D, Dense
import pandas as pd

# 데이터를 준비하고
(train_x, train_y), (test_x, test_y) = tf.keras.datasets.cifar10.load_data()

train_x = train_x / 255

# 모델을 만들고
model = Sequential()

model.add(Conv2D(??, (3, 3), input_shape=(32, 32, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(??, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Flatten())
model.add(Dense(??, activation='relu'))
model.add(Dense(??, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(train_x, train_y, epochs=10)